<?php require_once 'header.php'; function ere($value){return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');} ?>
<main class="content-body"><section class="page-section">
  <div class="section-title-bar"><div class="section-title"><i class="fa-solid fa-file-waveform"></i> Báo cáo số liệu EMR</div><a class="btn btn-outline" href="<?php echo XC_URL; ?>/backend/emrReport/template"><i class="fa-solid fa-download"></i> File mẫu</a><a class="btn btn-primary" href="<?php echo XC_URL; ?>/backend/emrReport/add"><i class="fa-solid fa-plus"></i> Nhập số liệu</a></div>
  <div class="filter-card"><form method="get" class="filter-grid" id="emrReportFilter"><div class="form-group"><label class="form-label">Từ ngày</label><input class="form-control" type="date" name="from_date" value="<?php echo ere($filterFromDate); ?>" required></div><div class="form-group"><label class="form-label">Đến ngày</label><input class="form-control" type="date" name="to_date" value="<?php echo ere($filterToDate); ?>" required></div><button class="btn btn-primary" style="align-self:end"><i class="fa-solid fa-filter"></i> Lọc</button></form></div>
  <div class="card" style="margin-bottom:18px"><div class="card-header"><div class="card-title">Tổng hợp theo bộ lọc</div></div><div class="card-body" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:16px">
    <div><div style="color:var(--text-muted);font-size:12px">Đã gửi EMR</div><strong style="font-size:22px"><?php echo number_format($totals->emr_sent_count); ?></strong></div><div><div style="color:var(--text-muted);font-size:12px">Đã ký</div><strong style="font-size:22px"><?php echo number_format($totals->emr_signed_count); ?></strong></div><div><div style="color:var(--text-muted);font-size:12px">Đã ký, chưa lưu trữ</div><strong style="font-size:22px"><?php echo number_format($totals->emr_signed_unarchived_count); ?></strong></div><div><div style="color:var(--text-muted);font-size:12px">Đã lưu trữ</div><strong style="font-size:22px"><?php echo number_format($totals->emr_archived_count); ?></strong></div><div><div style="color:var(--text-muted);font-size:12px">Lưu trữ chậm</div><strong style="font-size:22px"><?php echo number_format($totals->emr_archive_due_count); ?></strong></div><div><div style="color:var(--text-muted);font-size:12px">Lưu trữ đúng hạn</div><strong style="font-size:22px"><?php echo number_format($totals->emr_archive_on_time_count); ?></strong></div>
  </div></div>
  <div class="card"><div class="table-container"><table class="custom-table"><thead><tr><th>Ngày</th><th style="text-align:right">Đã gửi</th><th style="text-align:right">Đã ký</th><th style="text-align:right">Đã ký chưa lưu</th><th style="text-align:right">Đã lưu trữ</th><th style="text-align:right">Lưu chậm</th><th style="text-align:right">Lưu đúng hạn</th><th>Ghi chú</th><th style="text-align:center">Thao tác</th></tr></thead><tbody>
    <?php if(!$records): ?><tr><td colspan="9" style="text-align:center;padding:38px;color:var(--text-muted)"><i class="fa-regular fa-folder-open" style="display:block;font-size:28px;margin-bottom:10px"></i>Chưa có số liệu phù hợp.</td></tr><?php endif; foreach($records as $record): ?><tr><td style="font-weight:600;white-space:nowrap"><?php echo date('d/m/Y',strtotime($record->full_date)); ?></td><td style="text-align:right"><?php echo number_format($record->emr_sent_count); ?></td><td style="text-align:right"><?php echo number_format($record->emr_signed_count); ?></td><td style="text-align:right"><?php echo number_format($record->emr_signed_unarchived_count); ?></td><td style="text-align:right"><?php echo number_format($record->emr_archived_count); ?></td><td style="text-align:right"><?php echo number_format($record->emr_archive_due_count); ?></td><td style="text-align:right"><?php echo number_format($record->emr_archive_on_time_count); ?></td><td style="max-width:240px;white-space:normal"><?php echo $record->note!==null&&$record->note!==''?ere($record->note):'—'; ?></td><td><div class="action-btns" style="justify-content:center"><a class="btn-icon" title="Sửa" href="<?php echo XC_URL; ?>/backend/emrReport/edit/<?php echo (int)$record->id; ?>"><i class="fa-solid fa-pen"></i></a><button type="button" class="btn-icon delete" title="Xóa" data-id="<?php echo (int)$record->id; ?>"><i class="fa-solid fa-trash"></i></button></div></td></tr><?php endforeach; ?>
  </tbody></table></div></div>
</section></main>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script>(function($){$('#emrReportFilter').on('submit',function(e){if(this.from_date.value&&this.to_date.value&&this.from_date.value>this.to_date.value){e.preventDefault();Swal.fire('Khoảng ngày không hợp lệ','Từ ngày phải nhỏ hơn hoặc bằng đến ngày.','error');}});$('.btn-icon.delete').on('click',function(){var button=$(this),id=button.data('id');Swal.fire({title:'Xóa số liệu?',text:'Thao tác này sẽ xóa bản ghi EMR.',icon:'warning',showCancelButton:true,confirmButtonText:'Xóa',cancelButtonText:'Hủy'}).then(function(answer){if(!answer.isConfirmed)return;button.prop('disabled',true);$.ajax({url:'<?php echo XC_URL; ?>/api/deleteEmrReport',type:'POST',dataType:'json',data:{csrf:'<?php echo ere($csrf); ?>',id:id}}).done(function(response){Swal.fire({icon:response.success?'success':'error',title:response.success?'Thành công':'Không thành công',text:response.message,timer:response.success?1500:0,showConfirmButton:!response.success}).then(function(){if(response.success)location.reload();});}).fail(function(xhr){Swal.fire('Không thành công',(xhr.responseJSON&&xhr.responseJSON.message)||'Không thể xóa bản ghi. Vui lòng thử lại.','error');}).always(function(){button.prop('disabled',false);});});});})(jQuery);</script>
<?php require_once 'footer.php'; ?>
