<?php require_once 'header.php'; function ie($v) { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); } ?>
<main class="content-body"><section class="page-section">
  <div class="section-title-bar"><div class="section-title"><i class="fa-solid fa-bed-pulse"></i> Quản lý điều trị nội trú</div><a class="btn btn-primary" href="<?php echo XC_URL; ?>/backend/inpatient/add"><i class="fa-solid fa-plus"></i> Thêm số liệu</a></div>
  <div class="filter-card"><form method="get" class="filter-grid"><div class="form-group"><label class="form-label">Từ ngày</label><input class="form-control" type="date" name="from_date" value="<?php echo ie($_GET['from_date'] ?? ''); ?>"></div><div class="form-group"><label class="form-label">Đến ngày</label><input class="form-control" type="date" name="to_date" value="<?php echo ie($_GET['to_date'] ?? ''); ?>"></div><div class="form-group"><label class="form-label">Khoa điều trị</label><select class="form-select" name="department_id"><option value="">Tất cả</option><?php foreach($departments as $d): ?><option value="<?php echo (int)$d->id; ?>" <?php echo (!empty($_GET['department_id']) && (int)$_GET['department_id'] === (int)$d->id) ? 'selected' : ''; ?>><?php echo ie($d->department_name); ?></option><?php endforeach; ?></select></div><button class="btn btn-primary" style="align-self:end"><i class="fa-solid fa-filter"></i> Lọc</button></form></div>
  <div class="card"><div class="table-container"><table class="custom-table"><thead><tr><th>Ngày</th><th>Khoa điều trị</th><th style="text-align:right">Đầu ngày</th><th style="text-align:right">Nhập viện</th><th style="text-align:right">Ra viện</th><th style="text-align:right">Cuối ngày</th><th style="text-align:right">Ngày điều trị</th><th style="text-align:right">Giường dùng</th><th style="text-align:right">Công suất</th><th style="text-align:center">Thao tác</th></tr></thead><tbody><?php if (!$records): ?><tr><td colspan="10" style="text-align:center;padding:38px;color:var(--text-muted)"><i class="fa-regular fa-folder-open" style="display:block;font-size:28px;margin-bottom:10px"></i>Chưa có số liệu phù hợp.</td></tr><?php endif; foreach($records as $r): ?><tr><td style="font-weight:600;white-space:nowrap"><?php echo date('d/m/Y', strtotime($r->full_date)); ?></td><td><?php echo ie($r->department_name); ?></td><td style="text-align:right"><?php echo number_format($r->inpatient_opening_patient_count); ?></td><td style="text-align:right"><?php echo number_format($r->inpatient_admission_count); ?></td><td style="text-align:right"><?php echo number_format($r->inpatient_inpatient_daily_discharge_count); ?></td><td style="text-align:right;font-weight:600"><?php echo number_format($r->inpatient_closing_patient_count); ?></td><td style="text-align:right"><?php echo number_format($r->inpatient_treatment_days); ?></td><td style="text-align:right"><?php echo number_format($r->inpatient_occupied_beds); ?></td><td style="text-align:right"><?php echo $r->bed_occupancy_percent === null ? '—' : ie($r->bed_occupancy_percent) . '%'; ?></td><td><div class="action-btns" style="justify-content:center"><a class="btn-icon" title="Sửa" href="<?php echo XC_URL; ?>/backend/inpatient/edit/<?php echo (int)$r->id; ?>"><i class="fa-solid fa-pen"></i></a><button type="button" class="btn-icon delete" title="Xóa" data-id="<?php echo (int)$r->id; ?>"><i class="fa-solid fa-trash"></i></button></div></td></tr><?php endforeach; ?></tbody></table></div></div>
</section></main>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>$('.btn-icon.delete').on('click',function(){var button=$(this),id=button.data('id');Swal.fire({title:'Xóa bản ghi?',text:'Bản ghi sẽ được chuyển sang trạng thái đã xóa.',icon:'warning',showCancelButton:true,confirmButtonText:'Xóa',cancelButtonText:'Hủy'}).then(function(result){if(!result.isConfirmed)return;button.prop('disabled',true);$.ajax({url:'<?php echo XC_URL; ?>/api/deleteInpatient',type:'POST',dataType:'json',data:{csrf:'<?php echo ie($csrf); ?>',id:id}}).done(function(res){Swal.fire({icon:res.success?'success':'error',title:res.success?'Thành công':'Không thành công',text:res.message,timer:1600,showConfirmButton:false}).then(function(){if(res.success)location.reload();});}).fail(function(xhr){Swal.fire('Không thành công',(xhr.responseJSON&&xhr.responseJSON.message)||'Không thể xóa bản ghi. Vui lòng thử lại.','error');}).always(function(){button.prop('disabled',false);});});});</script>
<?php require_once 'footer.php'; ?>
